before_install:
  - travis_retry sudo apt-add-repository ppa:chris-lea/zeromq -y
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install libzmq3 libzmq3-dev -y
language: ruby
rvm:
  - 2.0.0
cache:
  - bundler
  - apt
